steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTest.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Install pre-release tool in $(StrykerInstallPath)'
    inputs:
      command: custom
      custom: tool
      arguments: update StrykerMutator.DotNetCoreCli --tool-path $(StrykerInstallPath) --version $(PreReleaseVersion) --add-source $(PreReleaseFeedUri)

  - task: DotNetCoreCLI@2
    displayName: 'Run integration test netstandard2.0'
    inputs:
      command: custom
      custom: stryker
      arguments: '--dev-mode'
      workingDirectory: $(IntegrationTestPath)/TargetProjects/NetStandard2_0/ExampleProject.XUnit
    
  - task: DotNetCoreCLI@2
    displayName: 'Run integration test netcoreapp2.1'
    inputs:
      command: custom
      custom: stryker
      arguments: '--dev-mode'
      workingDirectory: $(IntegrationTestPath)/TargetProjects/NetCore2_1/ExampleProject.XUnit

  - task: DotNetCoreCLI@2
    displayName: 'Assert integration test results'
    inputs:
      command: test
      projects: '$(IntegrationTestPath)/**/IntegrationTests.csproj'
      workingDirectory: $(IntegrationTestPath)