steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTest.csproj'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.300 because dotnet tools..'
    inputs:
      version: 2.1.300

  - task: DotNetCoreCLI@2
    displayName: 'Install pre-release dotnet tool'
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker -g --version $(PreReleaseVersion) --add-source $(PreReleaseFeedUri)

  - script: dotnet-stryker --dev-mode
    workingDirectory: $(IntegrationTestPath)/TargetProjects/NetStandardTestProject.XUnit
    displayName: 'Run integration test netstandard2.0'
    failOnStderr: false

  - script: dotnet stryker --dev-mode -tr vstest
    workingDirectory: $(IntegrationTestPath)/TargetProjects/NetCoreTestProject.XUnit
    displayName: 'Run integration test netstandard2.1'
    failOnStderr: false

  - task: DotNetCoreCLI@2
    displayName: 'Assert integration test results'
    inputs:
      command: test
      projects: '$(IntegrationTestPath)/ValidationProject/Validation.csproj'
      workingDirectory: $(IntegrationTestPath)