steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTest.csproj'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.1.300 because dotnet tools..'
    inputs:
    version: 2.1.300

  - task: DotNetCoreCLI@2
    displayName: 'Install pre-release dotnet tool'
    inputs:
      command: custom
      custom: tool
      arguments: install StrykerMutator.DotNetCoreCli -g --version $(PreReleaseVersion) --add-source $(PreReleaseFeedUri)

  - script: dotnet tool list
  - script: dotnet-stryker --dev-move
    workingDirectory: $(IntegrationTestPath)/TargetProjects/NetStandard2_0/ExampleProject.XUnit
    displayName: 'Run integration test netstandard2.0'
    failOnStderr: false
  - script: dotnet stryker --dev-move
    workingDirectory: $(IntegrationTestPath)/TargetProjects/NetStandard2_0/ExampleProject.XUnit
    displayName: 'Run integration test netstandard2.0'
    failOnStderr: false

  - script: dotnet stryker --dev-move
    workingDirectory: $(IntegrationTestPath)/TargetProjects/NetCore2_1/ExampleProject.XUnit
    displayName: 'Run integration test netstandard2.1'
    failOnStderr: false

  - task: DotNetCoreCLI@2
    displayName: 'Assert integration test results'
    inputs:
      command: test
      projects: '$(IntegrationTestPath)/**/IntegrationTests.csproj'
      workingDirectory: $(IntegrationTestPath)